import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Shield, Lock, FileText, AlertCircle, Sparkles, HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function Legal({ type }: { type: 'privacy' | 'terms' | 'disclaimer' | 'dmca' | 'cookies' | 'faq' | 'data-usage' | 'ai-transparency' }) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const content = {
    privacy: {
      title: 'Privacy Policy',
      icon: Shield,
      intro: 'Welcome to NerroPlay. Your privacy is paramount. We believe in total transparency regarding your data.',
      sections: [
        {
          title: "Information Collection",
          text: "We collect minimal data necessary for core functionality. This includes browser type, device identifiers, and tool usage logs. We DO NOT sell your personal information.",
          points: [
            "**Tool Interaction Logs**: Anonymous data on how you use our AI calculators.",
            "**Device & Browser Data**: For technical optimization.",
            "**Cookies**: For session persistence and preferences."
          ]
        },
        {
          title: "AI Processing Transparency",
          text: "When you use our AI tools (Health, Beauty, Finance), data is processed algorithmically. Your inputs are used to generate real-time results and are not stored in permanent databases unless explicitly requested."
        },
        {
          title: "Third-Party Partners",
          text: "We use Google AdSense for monetization and Google Analytics for performance tracking. These partners may use cookies to serve personalized ads based on your visit."
        }
      ]
    },
    terms: {
      title: 'Terms & Conditions',
      icon: FileText,
      intro: 'By accessing NerroPlay, you agree to these professional service terms.',
      sections: [
        {
          title: "Authorized Use",
          text: "Our tools are for educational and informational purposes. Commercial extraction or automated scraping of our AI results is strictly prohibited."
        },
        {
          title: "Tool Limitations",
          text: "Calculations provided are estimates based on mathematical algorithms. Users should always consult professionals for health, financial, or legal decisions."
        }
      ]
    },
    disclaimer: {
      title: 'Legal Disclaimer',
      icon: AlertCircle,
      intro: 'NerroPlay is a provider of algorithmic intelligence tools. Please read this disclaimer carefully.',
      sections: [
        {
          title: "Health & Fitness",
          text: "Tools like BMI, BMR, and Calorie calculators are for educational use. THEY ARE NOT MEDICAL ADVICE. Consult a healthcare provider before making significant lifestyle changes."
        },
        {
          title: "Financial Guidance",
          text: "Loan, SIP, and Profit calculators provide estimates only. These are not investment, tax, or legal advice. Accuracy is not guaranteed."
        },
        {
          title: "Spirituality & Lifestyle",
          text: "Kundli and Numerology tools provide spiritual guidance and symbolic interpretations. They should not be used as the sole basis for life-altering decisions."
        },
        {
          title: "AI Transparency",
          text: "Our AI insights are generated by large language models and neural networks. These are probabilistic systems and may occasionally produce varying results."
        }
      ]
    },
    cookies: {
      title: 'Cookie Policy',
      icon: Shield,
      intro: 'NerroPlay uses cookies to help improve your experience.',
      sections: [
        {
          title: "What are cookies?",
          text: "Cookies are small text files stored in your browser. They help us remember your settings (like Dark Mode) and analyze how our visitors interact with tools."
        },
        {
          title: "Your Choice",
          text: "You can manage or disable cookies via your browser settings. Note that some tools may lose functionality without session cookies."
        }
      ]
    },
    'ai-transparency': {
      title: 'AI Transparency Notice',
      icon: Sparkles,
      intro: 'How NerroPlay uses Artificial Intelligence responsibly.',
      sections: [
        {
          title: "Algorithmic Foundation",
          text: "Our tools use a two-layer approach: a deterministic mathematical engine for calculations, and a neural 'Insight Layer' for interpretation."
        },
        {
          title: "No Hidden Biases",
          text: "We strive to calibrate our AI models for neutrality and professional accuracy. AI results are informational and may vary depending on the model version."
        },
        {
          title: "Ethical AI Use",
          text: "We do not use AI to generate deceptive content. Our AI is designed to clarify, summarize, and provide context to data."
        }
      ]
    },
    'data-usage': {
      title: 'Data Usage Policy',
      icon: Lock,
      intro: 'How we handle and process the data you input.',
      sections: [
        {
          title: "Processing vs Storage",
          text: "Most tools process data 'in-flight'. This means your inputs are used to calculate the result and then discarded. We do not maintain long-term logs of individual health measurements or financial inputs."
        },
        {
          title: "Security Measures",
          text: "All data transmission is encrypted via HTTPS. We use standard Content Security Policies (CSP) to ensure your browser interacts safely with our servers."
        }
      ]
    },
    faq: {
      title: 'Global FAQ',
      icon: HelpCircle,
      intro: 'Finding answers to the most common questions about the NERROPLAY intelligence ecosystem.',
      sections: [
        {
          title: "What is NERROPLAY?",
          text: "NERROPLAY is a professional educational platform that provides AI-enhanced utility tools and calculators. Our mission is to provide high-precision algorithmic insights for health, finance, and lifestyle needs."
        },
        {
          title: "Is NERROPLAY free to use?",
          text: "Yes. All our core tools, calculators, and games are free for individual users. We sustain our operations through non-intrusive, responsible advertising and affiliate partnerships that are clearly marked."
        },
        {
          title: "How accurate are the AI insights?",
          text: "Our calculations use standard scientific and financial formulas (e.g., standard BMI formulas, compound interest models). The AI 'Insight Layer' provides context based on these numbers. While highly reliable, they should be used for educational purposes and not as a replacement for professional advice."
        },
        {
          title: "Is my data safe?",
          text: "NERROPLAY follows a 'Process-in-Flight' philosophy. Most inputs are used to calculate your result in real-time and are not stored in our databases. We use industry-standard encryption and security headers to protect your session."
        },
        {
          title: "Who builds the tools?",
          text: "The platform is maintained by the NERROPLAY Core engineering team. We regularly update our algorithms to reflect current scientific standards and financial regulations."
        },
        {
          title: "Can I use these results for medical or financial decisions?",
          text: "No. All tools on NERROPLAY are for informational and educational purposes only. You should always consult with a qualified doctor for health concerns or a financial advisor for investment decisions."
        },
        {
          title: "How does the AI transparency notice work?",
          text: "We believe in radical honesty. Any tool that uses AI explicitly mentions it, and we provide a dedicated AI Transparency page explaining the limitations and logic behind our neural systems."
        }
      ]
    },
    dmca: {
      title: 'DMCA Policy',
      icon: Lock,
      sections: [
        {
          title: "Copyright Protection",
          text: "Nerroplay respects intellectual property rights. If you believe any content infringes your rights, contact [admin@nerroplay.online]."
        }
      ]
    }
  }[type];

  return (
    <div className="pt-40 pb-20 px-4 max-w-4xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass p-8 md:p-12 rounded-[32px] md:rounded-[40px]"
      >
        <div className="w-16 h-16 rounded-2xl bg-surface flex items-center justify-center text-text-primary mb-8 border border-border-glass">
          <content.icon size={32} />
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-text-primary mb-8 tracking-tight">{content.title}</h1>
        <div className="prose prose-slate dark:prose-invert max-w-none text-text-secondary space-y-12 leading-relaxed text-lg">
          {(content as any).intro && (
            <p className="text-text-muted italic">{(content as any).intro}</p>
          )}
          
          {content.sections.map((section: any, idx) => (
            <div key={idx} className={`space-y-4 ${type === 'faq' ? 'glass overflow-hidden rounded-2xl border border-border-glass' : ''}`}>
              {type === 'faq' ? (
                <>
                  <button
                    onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
                    className="w-full flex items-center justify-between p-6 text-left hover:bg-white/5 transition-colors cursor-pointer group"
                  >
                    <h2 className="text-text-primary font-black text-lg md:text-xl uppercase tracking-tighter border-l-4 border-accent pl-4 flex-grow">
                      {section.title}
                    </h2>
                    <div className="ml-4 text-text-muted group-hover:text-accent transition-colors flex-shrink-0">
                      {openIndex === idx ? <ChevronUp size={24} /> : <ChevronDown size={24} />}
                    </div>
                  </button>
                  
                  <AnimatePresence initial={false}>
                    {openIndex === idx && (
                      <motion.div
                        key="content"
                        initial="collapsed"
                        animate="open"
                        exit="collapsed"
                        variants={{
                          open: { opacity: 1, height: "auto" },
                          collapsed: { opacity: 0, height: 0 }
                        }}
                        transition={{ duration: 0.3, ease: [0.04, 0.62, 0.23, 0.98] }}
                      >
                        <div className="p-6 pt-0 border-t border-border-glass bg-black/5 overflow-hidden">
                          <div className="text-sm md:text-base mt-4">
                            <span className="font-bold text-accent mr-2">A:</span>
                            <ReactMarkdown components={{
                              strong: ({children}) => <strong className="font-bold text-text-primary">{children}</strong>,
                              p: ({children}) => <p className="mb-2 last:mb-0 leading-relaxed">{children}</p>
                            }}>{section.text}</ReactMarkdown>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </>
              ) : (
                <>
                  <h2 className="text-text-primary font-black text-xl md:text-2xl uppercase tracking-tighter border-l-4 border-accent pl-4">
                    {`${idx + 1}. `}{section.title}
                  </h2>
                  
                  {section.text && (
                    <div className="text-sm md:text-base">
                      <ReactMarkdown components={{
                        strong: ({children}) => <strong className="font-bold text-text-primary">{children}</strong>,
                        p: ({children}) => <p className="mb-2 last:mb-0 leading-relaxed text-lg">{children}</p>
                      }}>{section.text}</ReactMarkdown>
                    </div>
                  )}
                  
                  {section.points && (
                    <ul className="list-disc pl-6 space-y-2 text-sm md:text-base">
                      {section.points.map((point: string, pIdx: number) => (
                        <li key={pIdx}>
                          <ReactMarkdown components={{
                            strong: ({children}) => <strong className="font-bold text-text-primary">{children}</strong>
                          }}>{point}</ReactMarkdown>
                        </li>
                      ))}
                    </ul>
                  )}
                  
                  {section.footer && (
                    <div className="text-sm md:text-base italic text-text-muted mt-6">
                       <ReactMarkdown components={{
                         strong: ({children}) => <strong className="font-bold text-text-primary">{children}</strong>
                       }}>{section.footer}</ReactMarkdown>
                    </div>
                  )}
                </>
              )}
            </div>
          ))}
          
          <div className="pt-12 border-t border-border-glass">
            <p className="text-xs font-mono uppercase tracking-widest text-text-muted">
              Last Updated: May 3, 2026. Nerroplay Reserves all rights.
            </p>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
