import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    // No-op - enforced English
  };

  // Simple translation helper
  const t = (key: string) => {
    return translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.tools': 'Tools',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Next-Gen Health Intelligence',
    'hero.subtitle': 'Empowering your fitness journey with AI-driven deep analysis and precision tracking.',
    'tools.title': 'Professional Toolbox',
    'tools.subtitle': 'Access our full suite of professional-grade utilities. Each tool is enhanced with AI Deep Analysis capabilities.',
    'ai.analysis.title': 'Nerro AI Deep Analysis',
    'ai.analysis.loading': 'Synthesizing Neural Matrix...',
    'ai.analysis.button': 'Nerro AI Deep Analysis',
    'ai.analysis.powered': 'Powered by Nerro AI Layer 2 Engine',
    'habit.trigger.title': 'Habit Trigger',
    'habit.trigger.water': '1 glass of water every hour = full body reset',
    'calc.button.bmi': 'Calculate BMI',
    'calc.button.calorie': 'Calculate TDEE',
    'calc.button.protein': 'Calculate Protein',
    'calc.button.water': 'Calculate Daily Goal',
    'water.title': 'Water Intake Calculator',
    'water.weight': 'Weight (kg)',
    'water.activity': 'Activity Level',
    'water.weather': 'Weather Conditions',
    'water.daily_goal': 'Daily Goal',
    'water.glasses_drank': 'Glasses Drank',
    'water.glasses_remaining': 'glasses remaining',
    'water.goal_achieved': 'Daily goal achieved! 🎉',
    'water.live_tracker': 'Live Water Tracker',
    'water.tracker_hint': 'Click + to track your progress throughout the day',
    'water.intelligence': 'Hydration Intelligence',
    'water.status': 'Status',
    'water.optimal': 'Optimal Hydration Required',
    'water.daily_intake': 'Daily Intake',
    'water.meaning': 'Detailed Meaning',
    'water.benefits': 'Hydration Benefits',
    'water.risks': 'Dehydration Risks',
    'water.plan': 'Smart Hydration Plan',
    'water.schedule': 'Daily Schedule',
    'water.tips': 'Lifestyle Tips',
    'water.habit_trigger': 'Habit Trigger',
    'water.habit_text': '"1 glass of water every hour = full body reset"',
    'bmi.title': 'BMI Calculator',
    'bmi.height': 'Height',
    'bmi.weight': 'Weight (kg)',
    'bmi.result': 'Your BMI',
    'bmi.category': 'Category',
    'bmi.underweight': 'Underweight',
    'bmi.normal': 'Normal',
    'bmi.overweight': 'Overweight',
    'bmi.obese': 'Obese',
    'sleep.title': 'Sleep Cycle Calculator',
    'sleep.mode_wake': 'I want to wake up at',
    'sleep.mode_now': 'I want to sleep now',
    'sleep.calculate': 'Calculate Sleep Cycles',
    'sleep.best_times': 'Best Times to Sleep',
    'sleep.best_wake': 'Best Times to Wake Up',
    'sleep.score': 'Sleep Score',
    'sleep.streak': 'Day Streak',
    'sleep.history': 'Sleep History',
    'sleep.status_optimized': 'Sleep timing is optimized',
    'sleep.status_poor': 'Sleep timing is poor',
    'sleep.meaning_title': 'Detailed Meaning',
    'sleep.benefits_title': 'Benefits',
    'sleep.risks_title': 'Poor Sleep Risks',
    'sleep.plan_title': 'Smart Sleep Plan',
    'sleep.routine_title': 'Daily Sleep Routine',
    'sleep.habit_trigger': 'Habit Trigger',
    'sleep.habit_text': '"Same time pe sone se body automatic recover hoti hai"',
    'sleep.hours': 'hours',
    'sleep.cycles': 'cycles',
    'sleep.fall_asleep': 'Includes 15 mins to fall asleep',
    'hr.title': 'Heart Rate Zone Calculator',
    'hr.age': 'Age',
    'hr.resting_hr': 'Resting Heart Rate (BPM)',
    'hr.goal': 'Fitness Goal',
    'hr.calculate': 'Calculate Zones',
    'hr.zone1': 'Zone 1 (Warm-up)',
    'hr.zone2': 'Zone 2 (Fat Burn)',
    'hr.zone3': 'Zone 3 (Cardio)',
    'hr.zone4': 'Zone 4 (Performance)',
    'hr.zone5': 'Zone 5 (Peak)',
    'hr.status': 'Optimal Fat Burn Zone',
    'hr.meaning': 'Heart Rate Training Science',
    'hr.fat_burn_strategy': 'Fat Burn Strategy',
    'hr.cardio_strategy': 'Cardio Strategy',
    'hr.performance_strategy': 'Performance Strategy',
    'hr.workout_plan': 'Weekly Workout Structure',
    'hr.risks': 'Overtraining & Risks',
    'hr.tips': 'Lifestyle & Recovery',
    'hr.habit_trigger': 'Habit Trigger',
    'hr.habit_text': '"Correct HR zone me workout = double results"',
    'hr.plan.fat_burn': 'Fat Burn Training Guide',
    'hr.plan.cardio': 'Cardio Improvement Plan',
    'hr.plan.endurance': 'Endurance Training',
    'hr.plan.peak': 'Peak Performance Strategy',
    'hr.view_plan': 'View Detailed Training Plan',
    'calorie.title': 'Calorie Calculator',
    'protein.title': 'Protein Calculator',
    'bmr.title': 'BMR',
    'height': 'Height',
    'common.age': 'Age',
    'common.gender': 'Gender',
    'common.male': 'Male',
    'common.female': 'Female',
    'common.weight': 'Weight',
    'common.height': 'Height',
    'common.activity': 'Activity Level',
    'common.goal': 'Fitness Goal',
    'common.calculate': 'Calculate',
    'common.results': 'Results',
    'common.status': 'Status',
    'common.meaning': 'Detailed Meaning',
    'common.diet': 'Diet Plan',
    'common.workout': 'Workout Plan',
    'common.lifestyle': 'Lifestyle Tips',
    'bodyfat.title': 'Body Fat Calculator',
    'bodyfat.smart_mode': 'Smart Mode',
    'bodyfat.advanced_mode': 'Advanced Mode',
    'bodyfat.body_type': 'Body Type',
    'bodyfat.slim': 'Slim',
    'bodyfat.fit': 'Fit',
    'bodyfat.average': 'Average',
    'bodyfat.heavy': 'Heavy',
    'bodyfat.neck': 'Neck (cm)',
    'bodyfat.waist': 'Waist (cm)',
    'bodyfat.hip': 'Hip (cm)',
    'bodyfat.preview_future': 'Preview Your Future Body',
    'bodyfat.ideal_range': 'Ideal Body Fat Range',
    'bodyfat.fat_loss_plan': 'Fat Loss Plan',
    'bodyfat.muscle_def': 'Muscle Definition Plan',
    'bodyfat.habit_trigger': 'Habit Trigger',
    'bodyfat.habit_text': '"Body fat control karo = real transformation start"',
    'bodyfat.current_body': 'Current Body',
    'bodyfat.target_body': 'Target Body',
  },
  hi: {
    'nav.home': 'होम',
    'nav.tools': 'टूल्स',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'hero.title': 'अगली पीढ़ी की स्वास्थ्य इंटेलिजेंस',
    'hero.subtitle': 'AI-संचालित गहन विश्लेषण और सटीक ट्रैकिंग के साथ आपकी फिटनेस यात्रा को सशक्त बनाना।',
    'tools.title': 'प्रोफेशनल टूलबॉक्स',
    'tools.subtitle': 'पेशेवर-ग्रेड उपयोगिताओं के हमारे पूर्ण सुइट तक पहुंचें। प्रत्येक टूल AI गहन विश्लेषण क्षमताओं के साथ बढ़ाया गया है।',
    'ai.analysis.title': 'Nerro AI गहन विश्लेषण',
    'ai.analysis.loading': 'न्यूरल मैट्रिक्स का संश्लेषण किया जा रहा है...',
    'ai.analysis.button': 'Nerro AI गहन विश्लेषण',
    'ai.analysis.powered': 'Nerro AI लेयर 2 इंजन द्वारा संचालित',
    'habit.trigger.title': 'आदत ट्रिगर',
    'habit.trigger.water': 'हर घंटे 1 गिलास पानी = फुल बॉडी रीसेट',
    'calc.button.bmi': 'BMI की गणना करें',
    'calc.button.calorie': 'TDEE की गणना करें',
    'calc.button.protein': 'प्रोटीन की गणना करें',
    'calc.button.water': 'दैनिक लक्ष्य की गणना करें',
    'water.title': 'पानी पीने का कैलकुलेटर',
    'water.weight': 'वजन (किलो)',
    'water.activity': 'गतिविधि का स्तर',
    'water.weather': 'मौसम की स्थिति',
    'water.daily_goal': 'दैनिक लक्ष्य',
    'water.glasses_drank': 'पिए गए गिलास',
    'water.glasses_remaining': 'गिलास शेष',
    'water.goal_achieved': 'दैनिक लक्ष्य पूरा हुआ! 🎉',
    'water.live_tracker': 'लाइव वॉटर ट्रैकर',
    'water.tracker_hint': 'दिन भर अपनी प्रगति को ट्रैक करने के लिए + पर क्लिक करें',
    'water.intelligence': 'हाइड्रेशन इंटेलिजेंस',
    'water.status': 'स्थिति',
    'water.optimal': 'इष्टतम हाइड्रेशन आवश्यक',
    'water.daily_intake': 'दैनिक सेवन',
    'water.meaning': 'विस्तृत अर्थ',
    'water.benefits': 'हाइड्रेशन के लाभ',
    'water.risks': 'निर्जलीकरण के जोखिम',
    'water.plan': 'स्मार्ट हाइड्रेशन प्लान',
    'water.schedule': 'दैनिक समय सारणी',
    'water.tips': 'जीवनशैली युक्तियाँ',
    'water.habit_trigger': 'आदत ट्रिगर',
    'water.habit_text': '"हर घंटे 1 गिलास पानी = फुल बॉडी रीसेट"',
    'bmi.title': 'BMI कैलकुलेटर',
    'bmi.height': 'ऊंचाई',
    'bmi.weight': 'वजन (किग्रा)',
    'bmi.result': 'आपका BMI',
    'bmi.category': 'श्रेणी',
    'bmi.underweight': 'कम वजन',
    'bmi.normal': 'सामान्य',
    'bmi.overweight': 'अधिक वजन',
    'bmi.obese': 'मोटापा',
    'sleep.title': 'स्लीप साइकिल कैलकुलेटर',
    'sleep.mode_wake': 'मैं इस समय जागना चाहता हूँ',
    'sleep.mode_now': 'मैं अभी सोना चाहता हूँ',
    'sleep.calculate': 'स्लीप साइकिल की गणना करें',
    'sleep.best_times': 'सोने का सबसे अच्छा समय',
    'sleep.best_wake': 'जागने का सबसे अच्छा समय',
    'sleep.score': 'स्लीप स्कोर',
    'sleep.streak': 'दिनों का सिलसिला',
    'sleep.history': 'नींद का इतिहास',
    'sleep.status_optimized': 'नींद का समय अनुकूलित है',
    'sleep.status_poor': 'नींद का समय खराब है',
    'sleep.meaning_title': 'विस्तृत अर्थ',
    'sleep.benefits_title': 'लाभ',
    'sleep.risks_title': 'खराब नींद के जोखिम',
    'sleep.plan_title': 'स्मार्ट स्लीप प्लान',
    'sleep.routine_title': 'दैनिक नींद की दिनचर्या',
    'sleep.habit_trigger': 'आदत ट्रिगर',
    'sleep.habit_text': '"एक ही समय पर सोने से बॉडी ऑटोमेटिक रिकवर होती है"',
    'sleep.hours': 'घंटे',
    'sleep.cycles': 'साइकिल',
    'sleep.fall_asleep': 'सोने के लिए 15 मिनट शामिल हैं',
    'hr.title': 'हार्ट रेट ज़ोन कैलकुलेटर',
    'hr.age': 'आयु',
    'hr.resting_hr': 'आराम के समय हृदय गति (BPM)',
    'hr.goal': 'फिटनेस लक्ष्य',
    'hr.calculate': 'ज़ोन की गणना करें',
    'hr.zone1': 'ज़ोन 1 (वार्म-अप)',
    'hr.zone2': 'ज़ोन 2 (फैट बर्न)',
    'hr.zone3': 'ज़ोन 3 (कार्डियो)',
    'hr.zone4': 'ज़ोन 4 (परफॉरमेंस)',
    'hr.zone5': 'ज़ोन 5 (पीक)',
    'hr.status': 'इष्टतम फैट बर्न ज़ोन',
    'hr.meaning': 'हार्ट रेट ट्रेनिंग विज्ञान',
    'hr.fat_burn_strategy': 'फैट बर्न रणनीति',
    'hr.cardio_strategy': 'कार्डियो रणनीति',
    'hr.performance_strategy': 'परफॉरमेंस रणनीति',
    'hr.workout_plan': 'साप्ताहिक वर्कआउट संरचना',
    'hr.risks': 'ओवरट्रेनिंग और जोखिम',
    'hr.tips': 'जीवनशैली और रिकवरी',
    'hr.habit_trigger': 'आदत ट्रिगर',
    'hr.habit_text': '"Correct HR zone me workout = double results"',
    'hr.plan.fat_burn': 'फैट बर्न ट्रेनिंग गाइड',
    'hr.plan.cardio': 'कार्डियो सुधार योजना',
    'hr.plan.endurance': 'सहनशक्ति प्रशिक्षण',
    'hr.plan.peak': 'पीक परफॉरमेंस रणनीति',
    'hr.view_plan': 'विस्तृत प्रशिक्षण योजना देखें',
    'bmr.title': 'BMR',
    'age': 'आयु',
    'gender': 'लिंग',
    'weight': 'वजन (kg)',
    'height': 'ऊंचाई',
    'calculate': 'BMR की गणना करें',
    'energy_type': 'ऊर्जा प्रकार',
    'daily_needs': 'दैनिक कैलोरी आवश्यकताएं',
    'fat_loss': 'फैट लॉस प्लान',
    'muscle_gain': 'मसल गेन प्लान',
    'diet': 'आहार रणनीति',
    'workout': 'वर्कआउट प्लान',
    'risks': 'जोखिम',
    'tips': 'जीवनशैली सुझाव',
    'habit_trigger': 'आदत ट्रिगर',
    'habit_text': '"Metabolism samjho — body control mein aayegi"',
    'calorie.title': 'कैलोरी कैलकुलेटर',
    'protein.title': 'प्रोटीन कैलकुलेटर',
    'common.age': 'आयु',
    'common.gender': 'लिंग',
    'common.male': 'पुरुष',
    'common.female': 'महिला',
    'common.weight': 'वजन',
    'common.height': 'ऊंचाई',
    'common.activity': 'गतिविधि का स्तर',
    'common.goal': 'फिटनेस लक्ष्य',
    'common.calculate': 'गणना करें',
    'common.results': 'परिणाम',
    'common.status': 'स्थिति',
    'common.meaning': 'विस्तृत अर्थ',
    'common.diet': 'आहार योजना',
    'common.workout': 'वर्कआउट प्लान',
    'common.lifestyle': 'जीवनशैली युक्तियाँ',
    'bodyfat.title': 'बॉडी फैट कैलकुलेटर',
    'bodyfat.smart_mode': 'स्मार्ट मोड',
    'bodyfat.advanced_mode': 'एडवांस मोड',
    'bodyfat.body_type': 'बॉडी टाइप',
    'bodyfat.slim': 'दुबला (Slim)',
    'bodyfat.fit': 'फिट (Fit)',
    'bodyfat.average': 'औसत (Average)',
    'bodyfat.heavy': 'भारी (Heavy)',
    'bodyfat.neck': 'गर्दन (सेमी)',
    'bodyfat.waist': 'कमर (सेमी)',
    'bodyfat.hip': 'कूल्हे (सेमी)',
    'bodyfat.preview_future': 'अपने भविष्य के शरीर का पूर्वावलोकन करें',
    'bodyfat.ideal_range': 'आदर्श बॉडी फैट रेंज',
    'bodyfat.fat_loss_plan': 'फैट लॉस प्लान',
    'bodyfat.muscle_def': 'मसल डेफिनेशन प्लान',
    'bodyfat.habit_trigger': 'आदत ट्रिगर',
    'bodyfat.habit_text': '"बॉडी फैट कंट्रोल करो = रियल ट्रांसफॉर्मेशन स्टार्ट"',
    'bodyfat.current_body': 'वर्तमान शरीर',
    'bodyfat.target_body': 'लक्ष्य शरीर',
  }
};
